cd /mnt/scratch/wenqi/FPGA-ANNS/unused/HBM_performance_test/HBM_bandwidth_test_struct_512_channels_28_freq_180_160
make cleanall
cd /mnt/scratch/wenqi/FPGA-ANNS/unused/HBM_performance_test/HBM_bandwidth_test_struct_512_channels_28_freq_200_150
make cleanall
cd /mnt/scratch/wenqi/FPGA-ANNS/unused/HBM_performance_test/HBM_bandwidth_test_struct_512_channels_28_freq_220_140
make cleanall
cd /mnt/scratch/wenqi/FPGA-ANNS/unused/HBM_performance_test/HBM_bandwidth_test_struct_512_channels_32
make cleanall
cd /mnt/scratch/wenqi/FPGA-ANNS/unused/HBM_performance_test/HBM_opt1
make cleanall
cd /mnt/scratch/wenqi/FPGA-ANNS/unused/HBM_performance_test/HBM_opt2
make cleanall
cd /mnt/scratch/wenqi/FPGA-ANNS/unused/HBM_performance_test/HBM_opt3
make cleanall
cd /mnt/scratch/wenqi/FPGA-ANNS/unused/HBM_performance_test/HBM_struct_PE_512_channels_28_freq_180
make cleanall
cd /mnt/scratch/wenqi/FPGA-ANNS/unused/HBM_performance_test/HBM_struct_PE_512_channels_28_freq_200
make cleanall
cd /mnt/scratch/wenqi/FPGA-ANNS/unused/HBM_performance_test/HBM_struct_add_all
make cleanall
cd /mnt/scratch/wenqi/FPGA-ANNS/unused/HBM_performance_test/HBM_struct_add_all_no_pragma
make cleanall
cd /mnt/scratch/wenqi/FPGA-ANNS/unused/HBM_performance_test/HBM_struct_add_reduction_no_pragma
make cleanall
cd /mnt/scratch/wenqi/FPGA-ANNS/unused/HBM_performance_test/HBM_struct_add_reduction_no_pragma_placement_opt1
make cleanall
cd /mnt/scratch/wenqi/FPGA-ANNS/unused/HBM_performance_test/HBM_struct_add_reduction_no_pragma_placement_opt2
make cleanall
