#include "constants.hpp"

extern "C" {
    
    // Top-level function
//////////////////////////////   TEMPLATE START  //////////////////////////////
    void vadd(
        const int *table0, const int *table1, const int *table2, 
        const int *table3, const int *table4, const int *table5, 
        const int *table6, const int *table7, const int *table8, 
        const int *table9, const int *table10, const int *table11, 
        const int *table12, const int *table13, const int *table14, 
        const int *table15, const int *table16, const int *table17, 
        const int *table18, const int *table19, const int *table20, 
        const int *table21, const int *table22, const int *table23, 
        const int *table24, const int *table25, const int *table26, 
        const int *table27, const int *table28, const int *table29, 
        const int *table30, const int *table31, const int *table32, 
        const int *table33, const int *table34, const int *table35, 
        const int *table36, const int *table37, const int *table38, 
        const int *table39, const int *table40, const int *table41, 
        const int *table42, const int *table43, const int *table44, 
        const int *table45, const int *table46, const int *table47, 
        const int *table48, const int *table49, const int *table50, 
        const int *table51, const int *table52, const int *table53, 
        const int *table54, const int *table55, const int *table56, 
        const int *table57, const int *table58, const int *table59, 
        const int *table60, const int *table61, const int *table62, 
        const int *table63, const int *table64, const int *table65, 
        const int *table66, const int *table67, const int *table68, 
        const int *table69, const int *table70, const int *table71, 
        const int *table72, const int *table73, const int *table74, 
        const int *table75, const int *table76, const int *table77, 
        const int *table78, const int *table79, const int *table80, 
        const int *table81, const int *table82, const int *table83, 
        const int *table84, const int *table85, const int *table86, 
        const int *table87, const int *table88, const int *table89, 
        const int *table90, const int *table91, const int *table92, 
        const int *table93, const int *table94, const int *table95, 
        const int *table96, const int *table97, const int *table98, 
        const int *table99, const int *table100, const int *table101, 
        const int *table102, const int *table103, const int *table104, 
        const int *table105, const int *table106, const int *table107, 
        const int *table108, const int *table109, const int *table110, 
        const int *table111, const int *table112, const int *table113, 
        const int *table114, const int *table115, const int *table116, 
        const int *table117, const int *table118, const int *table119, 
        const int *table120, const int *table121, const int *table122, 
        const int *table123, const int *table124, const int *table125, 
        const int *table126, const int *table127,
        const int *access_idx, int *out);
//////////////////////////////   TEMPLATE END  //////////////////////////////

    // load
    void load_single_embedding(
        int idx_buffer[BATCH_SIZE], const int* table_DRAM,
        int* embedding_buffer, int data_size);

//////////////////////////////   TEMPLATE START  //////////////////////////////
    void load_embeddings(
        const int* table0, const int* table1, const int* table2, const int* table3, 
        const int* table4, const int* table5, const int* table6, const int* table7, 
        const int* table8, const int* table9, const int* table10, const int* table11, 
        const int* table12, const int* table13, const int* table14, const int* table15, 
        const int* table16, const int* table17, const int* table18, const int* table19, 
        const int* table20, const int* table21, const int* table22, const int* table23, 
        const int* table24, const int* table25, const int* table26, const int* table27, 
        const int* table28, const int* table29, const int* table30, const int* table31, 
        const int* table32, const int* table33, const int* table34, const int* table35, 
        const int* table36, const int* table37, const int* table38, const int* table39, 
        const int* table40, const int* table41, const int* table42, const int* table43, 
        const int* table44, const int* table45, const int* table46, const int* table47, 
        const int* table48, const int* table49, const int* table50, const int* table51, 
        const int* table52, const int* table53, const int* table54, const int* table55, 
        const int* table56, const int* table57, const int* table58, const int* table59, 
        const int* table60, const int* table61, const int* table62, const int* table63, 
        const int* table64, const int* table65, const int* table66, const int* table67, 
        const int* table68, const int* table69, const int* table70, const int* table71, 
        const int* table72, const int* table73, const int* table74, const int* table75, 
        const int* table76, const int* table77, const int* table78, const int* table79, 
        const int* table80, const int* table81, const int* table82, const int* table83, 
        const int* table84, const int* table85, const int* table86, const int* table87, 
        const int* table88, const int* table89, const int* table90, const int* table91, 
        const int* table92, const int* table93, const int* table94, const int* table95, 
        const int* table96, const int* table97, const int* table98, const int* table99, 
        const int* table100, const int* table101, const int* table102, const int* table103, 
        const int* table104, const int* table105, const int* table106, const int* table107, 
        const int* table108, const int* table109, const int* table110, const int* table111, 
        const int* table112, const int* table113, const int* table114, const int* table115, 
        const int* table116, const int* table117, const int* table118, const int* table119, 
        const int* table120, const int* table121, const int* table122, const int* table123, 
        const int* table124, const int* table125, const int* table126, const int* table127,
        const int* access_idx, const int start_idx, 
        int embedding_buffer0[BATCH_SIZE * DATA_SIZE0], int embedding_buffer1[BATCH_SIZE * DATA_SIZE1], int embedding_buffer2[BATCH_SIZE * DATA_SIZE2], int embedding_buffer3[BATCH_SIZE * DATA_SIZE3], 
        int embedding_buffer4[BATCH_SIZE * DATA_SIZE4], int embedding_buffer5[BATCH_SIZE * DATA_SIZE5], int embedding_buffer6[BATCH_SIZE * DATA_SIZE6], int embedding_buffer7[BATCH_SIZE * DATA_SIZE7], 
        int embedding_buffer8[BATCH_SIZE * DATA_SIZE8], int embedding_buffer9[BATCH_SIZE * DATA_SIZE9], int embedding_buffer10[BATCH_SIZE * DATA_SIZE10], int embedding_buffer11[BATCH_SIZE * DATA_SIZE11], 
        int embedding_buffer12[BATCH_SIZE * DATA_SIZE12], int embedding_buffer13[BATCH_SIZE * DATA_SIZE13], int embedding_buffer14[BATCH_SIZE * DATA_SIZE14], int embedding_buffer15[BATCH_SIZE * DATA_SIZE15], 
        int embedding_buffer16[BATCH_SIZE * DATA_SIZE16], int embedding_buffer17[BATCH_SIZE * DATA_SIZE17], int embedding_buffer18[BATCH_SIZE * DATA_SIZE18], int embedding_buffer19[BATCH_SIZE * DATA_SIZE19], 
        int embedding_buffer20[BATCH_SIZE * DATA_SIZE20], int embedding_buffer21[BATCH_SIZE * DATA_SIZE21], int embedding_buffer22[BATCH_SIZE * DATA_SIZE22], int embedding_buffer23[BATCH_SIZE * DATA_SIZE23], 
        int embedding_buffer24[BATCH_SIZE * DATA_SIZE24], int embedding_buffer25[BATCH_SIZE * DATA_SIZE25], int embedding_buffer26[BATCH_SIZE * DATA_SIZE26], int embedding_buffer27[BATCH_SIZE * DATA_SIZE27], 
        int embedding_buffer28[BATCH_SIZE * DATA_SIZE28], int embedding_buffer29[BATCH_SIZE * DATA_SIZE29], int embedding_buffer30[BATCH_SIZE * DATA_SIZE30], int embedding_buffer31[BATCH_SIZE * DATA_SIZE31], 
        int embedding_buffer32[BATCH_SIZE * DATA_SIZE32], int embedding_buffer33[BATCH_SIZE * DATA_SIZE33], int embedding_buffer34[BATCH_SIZE * DATA_SIZE34], int embedding_buffer35[BATCH_SIZE * DATA_SIZE35], 
        int embedding_buffer36[BATCH_SIZE * DATA_SIZE36], int embedding_buffer37[BATCH_SIZE * DATA_SIZE37], int embedding_buffer38[BATCH_SIZE * DATA_SIZE38], int embedding_buffer39[BATCH_SIZE * DATA_SIZE39], 
        int embedding_buffer40[BATCH_SIZE * DATA_SIZE40], int embedding_buffer41[BATCH_SIZE * DATA_SIZE41], int embedding_buffer42[BATCH_SIZE * DATA_SIZE42], int embedding_buffer43[BATCH_SIZE * DATA_SIZE43], 
        int embedding_buffer44[BATCH_SIZE * DATA_SIZE44], int embedding_buffer45[BATCH_SIZE * DATA_SIZE45], int embedding_buffer46[BATCH_SIZE * DATA_SIZE46], int embedding_buffer47[BATCH_SIZE * DATA_SIZE47], 
        int embedding_buffer48[BATCH_SIZE * DATA_SIZE48], int embedding_buffer49[BATCH_SIZE * DATA_SIZE49], int embedding_buffer50[BATCH_SIZE * DATA_SIZE50], int embedding_buffer51[BATCH_SIZE * DATA_SIZE51], 
        int embedding_buffer52[BATCH_SIZE * DATA_SIZE52], int embedding_buffer53[BATCH_SIZE * DATA_SIZE53], int embedding_buffer54[BATCH_SIZE * DATA_SIZE54], int embedding_buffer55[BATCH_SIZE * DATA_SIZE55], 
        int embedding_buffer56[BATCH_SIZE * DATA_SIZE56], int embedding_buffer57[BATCH_SIZE * DATA_SIZE57], int embedding_buffer58[BATCH_SIZE * DATA_SIZE58], int embedding_buffer59[BATCH_SIZE * DATA_SIZE59], 
        int embedding_buffer60[BATCH_SIZE * DATA_SIZE60], int embedding_buffer61[BATCH_SIZE * DATA_SIZE61], int embedding_buffer62[BATCH_SIZE * DATA_SIZE62], int embedding_buffer63[BATCH_SIZE * DATA_SIZE63], 
        int embedding_buffer64[BATCH_SIZE * DATA_SIZE64], int embedding_buffer65[BATCH_SIZE * DATA_SIZE65], int embedding_buffer66[BATCH_SIZE * DATA_SIZE66], int embedding_buffer67[BATCH_SIZE * DATA_SIZE67], 
        int embedding_buffer68[BATCH_SIZE * DATA_SIZE68], int embedding_buffer69[BATCH_SIZE * DATA_SIZE69], int embedding_buffer70[BATCH_SIZE * DATA_SIZE70], int embedding_buffer71[BATCH_SIZE * DATA_SIZE71], 
        int embedding_buffer72[BATCH_SIZE * DATA_SIZE72], int embedding_buffer73[BATCH_SIZE * DATA_SIZE73], int embedding_buffer74[BATCH_SIZE * DATA_SIZE74], int embedding_buffer75[BATCH_SIZE * DATA_SIZE75], 
        int embedding_buffer76[BATCH_SIZE * DATA_SIZE76], int embedding_buffer77[BATCH_SIZE * DATA_SIZE77], int embedding_buffer78[BATCH_SIZE * DATA_SIZE78], int embedding_buffer79[BATCH_SIZE * DATA_SIZE79], 
        int embedding_buffer80[BATCH_SIZE * DATA_SIZE80], int embedding_buffer81[BATCH_SIZE * DATA_SIZE81], int embedding_buffer82[BATCH_SIZE * DATA_SIZE82], int embedding_buffer83[BATCH_SIZE * DATA_SIZE83], 
        int embedding_buffer84[BATCH_SIZE * DATA_SIZE84], int embedding_buffer85[BATCH_SIZE * DATA_SIZE85], int embedding_buffer86[BATCH_SIZE * DATA_SIZE86], int embedding_buffer87[BATCH_SIZE * DATA_SIZE87], 
        int embedding_buffer88[BATCH_SIZE * DATA_SIZE88], int embedding_buffer89[BATCH_SIZE * DATA_SIZE89], int embedding_buffer90[BATCH_SIZE * DATA_SIZE90], int embedding_buffer91[BATCH_SIZE * DATA_SIZE91], 
        int embedding_buffer92[BATCH_SIZE * DATA_SIZE92], int embedding_buffer93[BATCH_SIZE * DATA_SIZE93], int embedding_buffer94[BATCH_SIZE * DATA_SIZE94], int embedding_buffer95[BATCH_SIZE * DATA_SIZE95], 
        int embedding_buffer96[BATCH_SIZE * DATA_SIZE96], int embedding_buffer97[BATCH_SIZE * DATA_SIZE97], int embedding_buffer98[BATCH_SIZE * DATA_SIZE98], int embedding_buffer99[BATCH_SIZE * DATA_SIZE99], 
        int embedding_buffer100[BATCH_SIZE * DATA_SIZE100], int embedding_buffer101[BATCH_SIZE * DATA_SIZE101], int embedding_buffer102[BATCH_SIZE * DATA_SIZE102], int embedding_buffer103[BATCH_SIZE * DATA_SIZE103], 
        int embedding_buffer104[BATCH_SIZE * DATA_SIZE104], int embedding_buffer105[BATCH_SIZE * DATA_SIZE105], int embedding_buffer106[BATCH_SIZE * DATA_SIZE106], int embedding_buffer107[BATCH_SIZE * DATA_SIZE107], 
        int embedding_buffer108[BATCH_SIZE * DATA_SIZE108], int embedding_buffer109[BATCH_SIZE * DATA_SIZE109], int embedding_buffer110[BATCH_SIZE * DATA_SIZE110], int embedding_buffer111[BATCH_SIZE * DATA_SIZE111], 
        int embedding_buffer112[BATCH_SIZE * DATA_SIZE112], int embedding_buffer113[BATCH_SIZE * DATA_SIZE113], int embedding_buffer114[BATCH_SIZE * DATA_SIZE114], int embedding_buffer115[BATCH_SIZE * DATA_SIZE115], 
        int embedding_buffer116[BATCH_SIZE * DATA_SIZE116], int embedding_buffer117[BATCH_SIZE * DATA_SIZE117], int embedding_buffer118[BATCH_SIZE * DATA_SIZE118], int embedding_buffer119[BATCH_SIZE * DATA_SIZE119], 
        int embedding_buffer120[BATCH_SIZE * DATA_SIZE120], int embedding_buffer121[BATCH_SIZE * DATA_SIZE121], int embedding_buffer122[BATCH_SIZE * DATA_SIZE122], int embedding_buffer123[BATCH_SIZE * DATA_SIZE123], 
        int embedding_buffer124[BATCH_SIZE * DATA_SIZE124], int embedding_buffer125[BATCH_SIZE * DATA_SIZE125], int embedding_buffer126[BATCH_SIZE * DATA_SIZE126], int embedding_buffer127[BATCH_SIZE * DATA_SIZE127]
        );
//////////////////////////////   TEMPLATE END  //////////////////////////////

    // compute
    void reduction_add_single(
        int* embedding_buffer, int data_size, int result_buffer[BATCH_SIZE]);

//////////////////////////////   TEMPLATE START  //////////////////////////////
    void reduction_add_all(
        int embedding_buffer0[BATCH_SIZE * DATA_SIZE0], int embedding_buffer1[BATCH_SIZE * DATA_SIZE1], int embedding_buffer2[BATCH_SIZE * DATA_SIZE2], int embedding_buffer3[BATCH_SIZE * DATA_SIZE3], 
        int embedding_buffer4[BATCH_SIZE * DATA_SIZE4], int embedding_buffer5[BATCH_SIZE * DATA_SIZE5], int embedding_buffer6[BATCH_SIZE * DATA_SIZE6], int embedding_buffer7[BATCH_SIZE * DATA_SIZE7], 
        int embedding_buffer8[BATCH_SIZE * DATA_SIZE8], int embedding_buffer9[BATCH_SIZE * DATA_SIZE9], int embedding_buffer10[BATCH_SIZE * DATA_SIZE10], int embedding_buffer11[BATCH_SIZE * DATA_SIZE11], 
        int embedding_buffer12[BATCH_SIZE * DATA_SIZE12], int embedding_buffer13[BATCH_SIZE * DATA_SIZE13], int embedding_buffer14[BATCH_SIZE * DATA_SIZE14], int embedding_buffer15[BATCH_SIZE * DATA_SIZE15], 
        int embedding_buffer16[BATCH_SIZE * DATA_SIZE16], int embedding_buffer17[BATCH_SIZE * DATA_SIZE17], int embedding_buffer18[BATCH_SIZE * DATA_SIZE18], int embedding_buffer19[BATCH_SIZE * DATA_SIZE19], 
        int embedding_buffer20[BATCH_SIZE * DATA_SIZE20], int embedding_buffer21[BATCH_SIZE * DATA_SIZE21], int embedding_buffer22[BATCH_SIZE * DATA_SIZE22], int embedding_buffer23[BATCH_SIZE * DATA_SIZE23], 
        int embedding_buffer24[BATCH_SIZE * DATA_SIZE24], int embedding_buffer25[BATCH_SIZE * DATA_SIZE25], int embedding_buffer26[BATCH_SIZE * DATA_SIZE26], int embedding_buffer27[BATCH_SIZE * DATA_SIZE27], 
        int embedding_buffer28[BATCH_SIZE * DATA_SIZE28], int embedding_buffer29[BATCH_SIZE * DATA_SIZE29], int embedding_buffer30[BATCH_SIZE * DATA_SIZE30], int embedding_buffer31[BATCH_SIZE * DATA_SIZE31], 
        int embedding_buffer32[BATCH_SIZE * DATA_SIZE32], int embedding_buffer33[BATCH_SIZE * DATA_SIZE33], int embedding_buffer34[BATCH_SIZE * DATA_SIZE34], int embedding_buffer35[BATCH_SIZE * DATA_SIZE35], 
        int embedding_buffer36[BATCH_SIZE * DATA_SIZE36], int embedding_buffer37[BATCH_SIZE * DATA_SIZE37], int embedding_buffer38[BATCH_SIZE * DATA_SIZE38], int embedding_buffer39[BATCH_SIZE * DATA_SIZE39], 
        int embedding_buffer40[BATCH_SIZE * DATA_SIZE40], int embedding_buffer41[BATCH_SIZE * DATA_SIZE41], int embedding_buffer42[BATCH_SIZE * DATA_SIZE42], int embedding_buffer43[BATCH_SIZE * DATA_SIZE43], 
        int embedding_buffer44[BATCH_SIZE * DATA_SIZE44], int embedding_buffer45[BATCH_SIZE * DATA_SIZE45], int embedding_buffer46[BATCH_SIZE * DATA_SIZE46], int embedding_buffer47[BATCH_SIZE * DATA_SIZE47], 
        int embedding_buffer48[BATCH_SIZE * DATA_SIZE48], int embedding_buffer49[BATCH_SIZE * DATA_SIZE49], int embedding_buffer50[BATCH_SIZE * DATA_SIZE50], int embedding_buffer51[BATCH_SIZE * DATA_SIZE51], 
        int embedding_buffer52[BATCH_SIZE * DATA_SIZE52], int embedding_buffer53[BATCH_SIZE * DATA_SIZE53], int embedding_buffer54[BATCH_SIZE * DATA_SIZE54], int embedding_buffer55[BATCH_SIZE * DATA_SIZE55], 
        int embedding_buffer56[BATCH_SIZE * DATA_SIZE56], int embedding_buffer57[BATCH_SIZE * DATA_SIZE57], int embedding_buffer58[BATCH_SIZE * DATA_SIZE58], int embedding_buffer59[BATCH_SIZE * DATA_SIZE59], 
        int embedding_buffer60[BATCH_SIZE * DATA_SIZE60], int embedding_buffer61[BATCH_SIZE * DATA_SIZE61], int embedding_buffer62[BATCH_SIZE * DATA_SIZE62], int embedding_buffer63[BATCH_SIZE * DATA_SIZE63], 
        int embedding_buffer64[BATCH_SIZE * DATA_SIZE64], int embedding_buffer65[BATCH_SIZE * DATA_SIZE65], int embedding_buffer66[BATCH_SIZE * DATA_SIZE66], int embedding_buffer67[BATCH_SIZE * DATA_SIZE67], 
        int embedding_buffer68[BATCH_SIZE * DATA_SIZE68], int embedding_buffer69[BATCH_SIZE * DATA_SIZE69], int embedding_buffer70[BATCH_SIZE * DATA_SIZE70], int embedding_buffer71[BATCH_SIZE * DATA_SIZE71], 
        int embedding_buffer72[BATCH_SIZE * DATA_SIZE72], int embedding_buffer73[BATCH_SIZE * DATA_SIZE73], int embedding_buffer74[BATCH_SIZE * DATA_SIZE74], int embedding_buffer75[BATCH_SIZE * DATA_SIZE75], 
        int embedding_buffer76[BATCH_SIZE * DATA_SIZE76], int embedding_buffer77[BATCH_SIZE * DATA_SIZE77], int embedding_buffer78[BATCH_SIZE * DATA_SIZE78], int embedding_buffer79[BATCH_SIZE * DATA_SIZE79], 
        int embedding_buffer80[BATCH_SIZE * DATA_SIZE80], int embedding_buffer81[BATCH_SIZE * DATA_SIZE81], int embedding_buffer82[BATCH_SIZE * DATA_SIZE82], int embedding_buffer83[BATCH_SIZE * DATA_SIZE83], 
        int embedding_buffer84[BATCH_SIZE * DATA_SIZE84], int embedding_buffer85[BATCH_SIZE * DATA_SIZE85], int embedding_buffer86[BATCH_SIZE * DATA_SIZE86], int embedding_buffer87[BATCH_SIZE * DATA_SIZE87], 
        int embedding_buffer88[BATCH_SIZE * DATA_SIZE88], int embedding_buffer89[BATCH_SIZE * DATA_SIZE89], int embedding_buffer90[BATCH_SIZE * DATA_SIZE90], int embedding_buffer91[BATCH_SIZE * DATA_SIZE91], 
        int embedding_buffer92[BATCH_SIZE * DATA_SIZE92], int embedding_buffer93[BATCH_SIZE * DATA_SIZE93], int embedding_buffer94[BATCH_SIZE * DATA_SIZE94], int embedding_buffer95[BATCH_SIZE * DATA_SIZE95], 
        int embedding_buffer96[BATCH_SIZE * DATA_SIZE96], int embedding_buffer97[BATCH_SIZE * DATA_SIZE97], int embedding_buffer98[BATCH_SIZE * DATA_SIZE98], int embedding_buffer99[BATCH_SIZE * DATA_SIZE99], 
        int embedding_buffer100[BATCH_SIZE * DATA_SIZE100], int embedding_buffer101[BATCH_SIZE * DATA_SIZE101], int embedding_buffer102[BATCH_SIZE * DATA_SIZE102], int embedding_buffer103[BATCH_SIZE * DATA_SIZE103], 
        int embedding_buffer104[BATCH_SIZE * DATA_SIZE104], int embedding_buffer105[BATCH_SIZE * DATA_SIZE105], int embedding_buffer106[BATCH_SIZE * DATA_SIZE106], int embedding_buffer107[BATCH_SIZE * DATA_SIZE107], 
        int embedding_buffer108[BATCH_SIZE * DATA_SIZE108], int embedding_buffer109[BATCH_SIZE * DATA_SIZE109], int embedding_buffer110[BATCH_SIZE * DATA_SIZE110], int embedding_buffer111[BATCH_SIZE * DATA_SIZE111], 
        int embedding_buffer112[BATCH_SIZE * DATA_SIZE112], int embedding_buffer113[BATCH_SIZE * DATA_SIZE113], int embedding_buffer114[BATCH_SIZE * DATA_SIZE114], int embedding_buffer115[BATCH_SIZE * DATA_SIZE115], 
        int embedding_buffer116[BATCH_SIZE * DATA_SIZE116], int embedding_buffer117[BATCH_SIZE * DATA_SIZE117], int embedding_buffer118[BATCH_SIZE * DATA_SIZE118], int embedding_buffer119[BATCH_SIZE * DATA_SIZE119], 
        int embedding_buffer120[BATCH_SIZE * DATA_SIZE120], int embedding_buffer121[BATCH_SIZE * DATA_SIZE121], int embedding_buffer122[BATCH_SIZE * DATA_SIZE122], int embedding_buffer123[BATCH_SIZE * DATA_SIZE123], 
        int embedding_buffer124[BATCH_SIZE * DATA_SIZE124], int embedding_buffer125[BATCH_SIZE * DATA_SIZE125], int embedding_buffer126[BATCH_SIZE * DATA_SIZE126], int embedding_buffer127[BATCH_SIZE * DATA_SIZE127], 
        int vout_buffer[BATCH_SIZE]);
//////////////////////////////   TEMPLATE END  //////////////////////////////

    // write output
    void write_results(int vout_buffer[BATCH_SIZE], 
        int* out, int start_idx);
}