-- Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
-- --------------------------------------------------------------------------------
-- Tool Version: Vivado v.2020.2 (lin64) Build 3064766 Wed Nov 18 09:12:47 MST 2020
-- Date        : Sun Jun 20 17:12:53 2021
-- Host        : alveo0 running 64-bit Ubuntu 18.04.3 LTS
-- Command     : write_vhdl -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix
--               decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ pfm_dynamic_vadd_1_0_stub.vhdl
-- Design      : pfm_dynamic_vadd_1_0
-- Purpose     : Stub declaration of top-level module interface
-- Device      : xcu280-fsvh2892-2L-e
-- --------------------------------------------------------------------------------
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix is
  Port ( 
    stall_start_ext : out STD_LOGIC;
    stall_done_ext : out STD_LOGIC;
    stall_start_str : out STD_LOGIC;
    stall_done_str : out STD_LOGIC;
    stall_start_int : out STD_LOGIC;
    stall_done_int : out STD_LOGIC;
    s_axi_control_AWADDR : in STD_LOGIC_VECTOR ( 6 downto 0 );
    s_axi_control_AWVALID : in STD_LOGIC;
    s_axi_control_AWREADY : out STD_LOGIC;
    s_axi_control_WDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    s_axi_control_WSTRB : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s_axi_control_WVALID : in STD_LOGIC;
    s_axi_control_WREADY : out STD_LOGIC;
    s_axi_control_BRESP : out STD_LOGIC_VECTOR ( 1 downto 0 );
    s_axi_control_BVALID : out STD_LOGIC;
    s_axi_control_BREADY : in STD_LOGIC;
    s_axi_control_ARADDR : in STD_LOGIC_VECTOR ( 6 downto 0 );
    s_axi_control_ARVALID : in STD_LOGIC;
    s_axi_control_ARREADY : out STD_LOGIC;
    s_axi_control_RDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    s_axi_control_RRESP : out STD_LOGIC_VECTOR ( 1 downto 0 );
    s_axi_control_RVALID : out STD_LOGIC;
    s_axi_control_RREADY : in STD_LOGIC;
    ap_clk : in STD_LOGIC;
    ap_rst_n : in STD_LOGIC;
    event_done : out STD_LOGIC;
    interrupt : out STD_LOGIC;
    event_start : out STD_LOGIC;
    m_axi_gmem21_AWADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_gmem21_AWLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_gmem21_AWSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem21_AWBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem21_AWLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem21_AWREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem21_AWCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem21_AWPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem21_AWQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem21_AWVALID : out STD_LOGIC;
    m_axi_gmem21_AWREADY : in STD_LOGIC;
    m_axi_gmem21_WDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_gmem21_WSTRB : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem21_WLAST : out STD_LOGIC;
    m_axi_gmem21_WVALID : out STD_LOGIC;
    m_axi_gmem21_WREADY : in STD_LOGIC;
    m_axi_gmem21_BRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem21_BVALID : in STD_LOGIC;
    m_axi_gmem21_BREADY : out STD_LOGIC;
    m_axi_gmem21_ARADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_gmem21_ARLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_gmem21_ARSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem21_ARBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem21_ARLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem21_ARREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem21_ARCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem21_ARPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem21_ARQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem21_ARVALID : out STD_LOGIC;
    m_axi_gmem21_ARREADY : in STD_LOGIC;
    m_axi_gmem21_RDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_gmem21_RRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem21_RLAST : in STD_LOGIC;
    m_axi_gmem21_RVALID : in STD_LOGIC;
    m_axi_gmem21_RREADY : out STD_LOGIC;
    m_axi_gmem22_AWADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_gmem22_AWLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_gmem22_AWSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem22_AWBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem22_AWLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem22_AWREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem22_AWCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem22_AWPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem22_AWQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem22_AWVALID : out STD_LOGIC;
    m_axi_gmem22_AWREADY : in STD_LOGIC;
    m_axi_gmem22_WDATA : out STD_LOGIC_VECTOR ( 511 downto 0 );
    m_axi_gmem22_WSTRB : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_gmem22_WLAST : out STD_LOGIC;
    m_axi_gmem22_WVALID : out STD_LOGIC;
    m_axi_gmem22_WREADY : in STD_LOGIC;
    m_axi_gmem22_BRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem22_BVALID : in STD_LOGIC;
    m_axi_gmem22_BREADY : out STD_LOGIC;
    m_axi_gmem22_ARADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_gmem22_ARLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_gmem22_ARSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem22_ARBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem22_ARLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem22_ARREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem22_ARCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem22_ARPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem22_ARQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem22_ARVALID : out STD_LOGIC;
    m_axi_gmem22_ARREADY : in STD_LOGIC;
    m_axi_gmem22_RDATA : in STD_LOGIC_VECTOR ( 511 downto 0 );
    m_axi_gmem22_RRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem22_RLAST : in STD_LOGIC;
    m_axi_gmem22_RVALID : in STD_LOGIC;
    m_axi_gmem22_RREADY : out STD_LOGIC;
    m_axi_gmem23_AWADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_gmem23_AWLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_gmem23_AWSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem23_AWBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem23_AWLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem23_AWREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem23_AWCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem23_AWPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem23_AWQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem23_AWVALID : out STD_LOGIC;
    m_axi_gmem23_AWREADY : in STD_LOGIC;
    m_axi_gmem23_WDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_gmem23_WSTRB : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem23_WLAST : out STD_LOGIC;
    m_axi_gmem23_WVALID : out STD_LOGIC;
    m_axi_gmem23_WREADY : in STD_LOGIC;
    m_axi_gmem23_BRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem23_BVALID : in STD_LOGIC;
    m_axi_gmem23_BREADY : out STD_LOGIC;
    m_axi_gmem23_ARADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_gmem23_ARLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_gmem23_ARSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem23_ARBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem23_ARLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem23_ARREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem23_ARCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem23_ARPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem23_ARQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem23_ARVALID : out STD_LOGIC;
    m_axi_gmem23_ARREADY : in STD_LOGIC;
    m_axi_gmem23_RDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_gmem23_RRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem23_RLAST : in STD_LOGIC;
    m_axi_gmem23_RVALID : in STD_LOGIC;
    m_axi_gmem23_RREADY : out STD_LOGIC;
    m_axi_gmem24_AWADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_gmem24_AWLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_gmem24_AWSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem24_AWBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem24_AWLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem24_AWREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem24_AWCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem24_AWPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem24_AWQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem24_AWVALID : out STD_LOGIC;
    m_axi_gmem24_AWREADY : in STD_LOGIC;
    m_axi_gmem24_WDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_gmem24_WSTRB : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem24_WLAST : out STD_LOGIC;
    m_axi_gmem24_WVALID : out STD_LOGIC;
    m_axi_gmem24_WREADY : in STD_LOGIC;
    m_axi_gmem24_BRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem24_BVALID : in STD_LOGIC;
    m_axi_gmem24_BREADY : out STD_LOGIC;
    m_axi_gmem24_ARADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_gmem24_ARLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_gmem24_ARSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem24_ARBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem24_ARLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem24_ARREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem24_ARCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem24_ARPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem24_ARQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem24_ARVALID : out STD_LOGIC;
    m_axi_gmem24_ARREADY : in STD_LOGIC;
    m_axi_gmem24_RDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_gmem24_RRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem24_RLAST : in STD_LOGIC;
    m_axi_gmem24_RVALID : in STD_LOGIC;
    m_axi_gmem24_RREADY : out STD_LOGIC;
    m_axi_gmem25_AWADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_gmem25_AWLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_gmem25_AWSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem25_AWBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem25_AWLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem25_AWREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem25_AWCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem25_AWPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem25_AWQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem25_AWVALID : out STD_LOGIC;
    m_axi_gmem25_AWREADY : in STD_LOGIC;
    m_axi_gmem25_WDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_gmem25_WSTRB : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem25_WLAST : out STD_LOGIC;
    m_axi_gmem25_WVALID : out STD_LOGIC;
    m_axi_gmem25_WREADY : in STD_LOGIC;
    m_axi_gmem25_BRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem25_BVALID : in STD_LOGIC;
    m_axi_gmem25_BREADY : out STD_LOGIC;
    m_axi_gmem25_ARADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_gmem25_ARLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_gmem25_ARSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem25_ARBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem25_ARLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem25_ARREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem25_ARCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem25_ARPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem25_ARQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem25_ARVALID : out STD_LOGIC;
    m_axi_gmem25_ARREADY : in STD_LOGIC;
    m_axi_gmem25_RDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_gmem25_RRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem25_RLAST : in STD_LOGIC;
    m_axi_gmem25_RVALID : in STD_LOGIC;
    m_axi_gmem25_RREADY : out STD_LOGIC;
    m_axi_gmem34_AWADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_gmem34_AWLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_gmem34_AWSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem34_AWBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem34_AWLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem34_AWREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem34_AWCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem34_AWPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem34_AWQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem34_AWVALID : out STD_LOGIC;
    m_axi_gmem34_AWREADY : in STD_LOGIC;
    m_axi_gmem34_WDATA : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_gmem34_WSTRB : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_gmem34_WLAST : out STD_LOGIC;
    m_axi_gmem34_WVALID : out STD_LOGIC;
    m_axi_gmem34_WREADY : in STD_LOGIC;
    m_axi_gmem34_BRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem34_BVALID : in STD_LOGIC;
    m_axi_gmem34_BREADY : out STD_LOGIC;
    m_axi_gmem34_ARADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_gmem34_ARLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_gmem34_ARSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem34_ARBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem34_ARLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem34_ARREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem34_ARCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem34_ARPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem34_ARQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem34_ARVALID : out STD_LOGIC;
    m_axi_gmem34_ARREADY : in STD_LOGIC;
    m_axi_gmem34_RDATA : in STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_gmem34_RRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem34_RLAST : in STD_LOGIC;
    m_axi_gmem34_RVALID : in STD_LOGIC;
    m_axi_gmem34_RREADY : out STD_LOGIC
  );

end decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix;

architecture stub of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix is
attribute syn_black_box : boolean;
attribute black_box_pad_pin : string;
attribute syn_black_box of stub : architecture is true;
attribute black_box_pad_pin of stub : architecture is "stall_start_ext,stall_done_ext,stall_start_str,stall_done_str,stall_start_int,stall_done_int,s_axi_control_AWADDR[6:0],s_axi_control_AWVALID,s_axi_control_AWREADY,s_axi_control_WDATA[31:0],s_axi_control_WSTRB[3:0],s_axi_control_WVALID,s_axi_control_WREADY,s_axi_control_BRESP[1:0],s_axi_control_BVALID,s_axi_control_BREADY,s_axi_control_ARADDR[6:0],s_axi_control_ARVALID,s_axi_control_ARREADY,s_axi_control_RDATA[31:0],s_axi_control_RRESP[1:0],s_axi_control_RVALID,s_axi_control_RREADY,ap_clk,ap_rst_n,event_done,interrupt,event_start,m_axi_gmem21_AWADDR[63:0],m_axi_gmem21_AWLEN[7:0],m_axi_gmem21_AWSIZE[2:0],m_axi_gmem21_AWBURST[1:0],m_axi_gmem21_AWLOCK[1:0],m_axi_gmem21_AWREGION[3:0],m_axi_gmem21_AWCACHE[3:0],m_axi_gmem21_AWPROT[2:0],m_axi_gmem21_AWQOS[3:0],m_axi_gmem21_AWVALID,m_axi_gmem21_AWREADY,m_axi_gmem21_WDATA[31:0],m_axi_gmem21_WSTRB[3:0],m_axi_gmem21_WLAST,m_axi_gmem21_WVALID,m_axi_gmem21_WREADY,m_axi_gmem21_BRESP[1:0],m_axi_gmem21_BVALID,m_axi_gmem21_BREADY,m_axi_gmem21_ARADDR[63:0],m_axi_gmem21_ARLEN[7:0],m_axi_gmem21_ARSIZE[2:0],m_axi_gmem21_ARBURST[1:0],m_axi_gmem21_ARLOCK[1:0],m_axi_gmem21_ARREGION[3:0],m_axi_gmem21_ARCACHE[3:0],m_axi_gmem21_ARPROT[2:0],m_axi_gmem21_ARQOS[3:0],m_axi_gmem21_ARVALID,m_axi_gmem21_ARREADY,m_axi_gmem21_RDATA[31:0],m_axi_gmem21_RRESP[1:0],m_axi_gmem21_RLAST,m_axi_gmem21_RVALID,m_axi_gmem21_RREADY,m_axi_gmem22_AWADDR[63:0],m_axi_gmem22_AWLEN[7:0],m_axi_gmem22_AWSIZE[2:0],m_axi_gmem22_AWBURST[1:0],m_axi_gmem22_AWLOCK[1:0],m_axi_gmem22_AWREGION[3:0],m_axi_gmem22_AWCACHE[3:0],m_axi_gmem22_AWPROT[2:0],m_axi_gmem22_AWQOS[3:0],m_axi_gmem22_AWVALID,m_axi_gmem22_AWREADY,m_axi_gmem22_WDATA[511:0],m_axi_gmem22_WSTRB[63:0],m_axi_gmem22_WLAST,m_axi_gmem22_WVALID,m_axi_gmem22_WREADY,m_axi_gmem22_BRESP[1:0],m_axi_gmem22_BVALID,m_axi_gmem22_BREADY,m_axi_gmem22_ARADDR[63:0],m_axi_gmem22_ARLEN[7:0],m_axi_gmem22_ARSIZE[2:0],m_axi_gmem22_ARBURST[1:0],m_axi_gmem22_ARLOCK[1:0],m_axi_gmem22_ARREGION[3:0],m_axi_gmem22_ARCACHE[3:0],m_axi_gmem22_ARPROT[2:0],m_axi_gmem22_ARQOS[3:0],m_axi_gmem22_ARVALID,m_axi_gmem22_ARREADY,m_axi_gmem22_RDATA[511:0],m_axi_gmem22_RRESP[1:0],m_axi_gmem22_RLAST,m_axi_gmem22_RVALID,m_axi_gmem22_RREADY,m_axi_gmem23_AWADDR[63:0],m_axi_gmem23_AWLEN[7:0],m_axi_gmem23_AWSIZE[2:0],m_axi_gmem23_AWBURST[1:0],m_axi_gmem23_AWLOCK[1:0],m_axi_gmem23_AWREGION[3:0],m_axi_gmem23_AWCACHE[3:0],m_axi_gmem23_AWPROT[2:0],m_axi_gmem23_AWQOS[3:0],m_axi_gmem23_AWVALID,m_axi_gmem23_AWREADY,m_axi_gmem23_WDATA[31:0],m_axi_gmem23_WSTRB[3:0],m_axi_gmem23_WLAST,m_axi_gmem23_WVALID,m_axi_gmem23_WREADY,m_axi_gmem23_BRESP[1:0],m_axi_gmem23_BVALID,m_axi_gmem23_BREADY,m_axi_gmem23_ARADDR[63:0],m_axi_gmem23_ARLEN[7:0],m_axi_gmem23_ARSIZE[2:0],m_axi_gmem23_ARBURST[1:0],m_axi_gmem23_ARLOCK[1:0],m_axi_gmem23_ARREGION[3:0],m_axi_gmem23_ARCACHE[3:0],m_axi_gmem23_ARPROT[2:0],m_axi_gmem23_ARQOS[3:0],m_axi_gmem23_ARVALID,m_axi_gmem23_ARREADY,m_axi_gmem23_RDATA[31:0],m_axi_gmem23_RRESP[1:0],m_axi_gmem23_RLAST,m_axi_gmem23_RVALID,m_axi_gmem23_RREADY,m_axi_gmem24_AWADDR[63:0],m_axi_gmem24_AWLEN[7:0],m_axi_gmem24_AWSIZE[2:0],m_axi_gmem24_AWBURST[1:0],m_axi_gmem24_AWLOCK[1:0],m_axi_gmem24_AWREGION[3:0],m_axi_gmem24_AWCACHE[3:0],m_axi_gmem24_AWPROT[2:0],m_axi_gmem24_AWQOS[3:0],m_axi_gmem24_AWVALID,m_axi_gmem24_AWREADY,m_axi_gmem24_WDATA[31:0],m_axi_gmem24_WSTRB[3:0],m_axi_gmem24_WLAST,m_axi_gmem24_WVALID,m_axi_gmem24_WREADY,m_axi_gmem24_BRESP[1:0],m_axi_gmem24_BVALID,m_axi_gmem24_BREADY,m_axi_gmem24_ARADDR[63:0],m_axi_gmem24_ARLEN[7:0],m_axi_gmem24_ARSIZE[2:0],m_axi_gmem24_ARBURST[1:0],m_axi_gmem24_ARLOCK[1:0],m_axi_gmem24_ARREGION[3:0],m_axi_gmem24_ARCACHE[3:0],m_axi_gmem24_ARPROT[2:0],m_axi_gmem24_ARQOS[3:0],m_axi_gmem24_ARVALID,m_axi_gmem24_ARREADY,m_axi_gmem24_RDATA[31:0],m_axi_gmem24_RRESP[1:0],m_axi_gmem24_RLAST,m_axi_gmem24_RVALID,m_axi_gmem24_RREADY,m_axi_gmem25_AWADDR[63:0],m_axi_gmem25_AWLEN[7:0],m_axi_gmem25_AWSIZE[2:0],m_axi_gmem25_AWBURST[1:0],m_axi_gmem25_AWLOCK[1:0],m_axi_gmem25_AWREGION[3:0],m_axi_gmem25_AWCACHE[3:0],m_axi_gmem25_AWPROT[2:0],m_axi_gmem25_AWQOS[3:0],m_axi_gmem25_AWVALID,m_axi_gmem25_AWREADY,m_axi_gmem25_WDATA[31:0],m_axi_gmem25_WSTRB[3:0],m_axi_gmem25_WLAST,m_axi_gmem25_WVALID,m_axi_gmem25_WREADY,m_axi_gmem25_BRESP[1:0],m_axi_gmem25_BVALID,m_axi_gmem25_BREADY,m_axi_gmem25_ARADDR[63:0],m_axi_gmem25_ARLEN[7:0],m_axi_gmem25_ARSIZE[2:0],m_axi_gmem25_ARBURST[1:0],m_axi_gmem25_ARLOCK[1:0],m_axi_gmem25_ARREGION[3:0],m_axi_gmem25_ARCACHE[3:0],m_axi_gmem25_ARPROT[2:0],m_axi_gmem25_ARQOS[3:0],m_axi_gmem25_ARVALID,m_axi_gmem25_ARREADY,m_axi_gmem25_RDATA[31:0],m_axi_gmem25_RRESP[1:0],m_axi_gmem25_RLAST,m_axi_gmem25_RVALID,m_axi_gmem25_RREADY,m_axi_gmem34_AWADDR[63:0],m_axi_gmem34_AWLEN[7:0],m_axi_gmem34_AWSIZE[2:0],m_axi_gmem34_AWBURST[1:0],m_axi_gmem34_AWLOCK[1:0],m_axi_gmem34_AWREGION[3:0],m_axi_gmem34_AWCACHE[3:0],m_axi_gmem34_AWPROT[2:0],m_axi_gmem34_AWQOS[3:0],m_axi_gmem34_AWVALID,m_axi_gmem34_AWREADY,m_axi_gmem34_WDATA[63:0],m_axi_gmem34_WSTRB[7:0],m_axi_gmem34_WLAST,m_axi_gmem34_WVALID,m_axi_gmem34_WREADY,m_axi_gmem34_BRESP[1:0],m_axi_gmem34_BVALID,m_axi_gmem34_BREADY,m_axi_gmem34_ARADDR[63:0],m_axi_gmem34_ARLEN[7:0],m_axi_gmem34_ARSIZE[2:0],m_axi_gmem34_ARBURST[1:0],m_axi_gmem34_ARLOCK[1:0],m_axi_gmem34_ARREGION[3:0],m_axi_gmem34_ARCACHE[3:0],m_axi_gmem34_ARPROT[2:0],m_axi_gmem34_ARQOS[3:0],m_axi_gmem34_ARVALID,m_axi_gmem34_ARREADY,m_axi_gmem34_RDATA[63:0],m_axi_gmem34_RRESP[1:0],m_axi_gmem34_RLAST,m_axi_gmem34_RVALID,m_axi_gmem34_RREADY";
attribute X_CORE_INFO : string;
attribute X_CORE_INFO of stub : architecture is "vadd,Vivado 2020.2";
begin
end;
